#!/usr/bin/env python3

#  LocBkp - a small backup script
#  Copyright (C) 2022  Locchan <locchan@protonmail.com>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  (version 2) as published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import argparse
import os

import logging

from locbkp.utils.utils import get_logger, set_default_logger

version = "0.0.6b"

if os.name == "nt":
    logdir = "./logs"
else:
    logdir = "/var/log/services/LocBkp/"

log_path = os.path.join(logdir, "Locbkp.log")

if not os.path.exists(logdir):
    os.makedirs(logdir)

logger = get_logger(level=logging.INFO, logpath=log_path, redefine_default=True)

from locbkp.Backup import Backup

logger.info("=== LocBkp v.{} started ===".format(version))

parser = argparse.ArgumentParser()
parser.add_argument("--configs", help="Backup lists to use.", type=str)
args = parser.parse_args()

if args.configs is not None:
    backup_lists = args.configs.split(" ")
else:
    logger.info("No configs provided. Cannot start.")
    exit(1)

for alist in backup_lists:
    backup = Backup(alist)
    if backup.backup_list:
        backup_result_file = backup.start()


